EntretienVannes/EntretienVannes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from appliVanne import views




urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('appliVanne.urls')),
    path('',include('applicompte.urls')),
    path('tinymce/', include('tinymce.urls')),  
]

handler404 = 'appliVanne.views.handler404'
handler500 = 'appliVanne.views.handler500'

EntretienVannes/appliVanne/urls.py
from django.contrib import admin
from django.urls import path
from appliVanne import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500



urlpatterns = [
    path("vannes/", views.listeVanne, name="vannes"),
    path("dump/", views.rechercheVanne, name="dump"),
    path("recherche/", views.rechercheAJAX),
    path("rechangeREG/", views.rechangeREG, name="rechangeREG"),
    path("rechangeTOR/", views.rechangeTOR, name="rechangeTOR"),
    path("actionneur/", views.actionneur, name="actionneur"),
    path("", views.listeVanne, name="home"),
    path('vanne/<int:id_vanne>/detail', views.detailVanne, name='detail_vanne'),
    path('vanne/<int:id_vanne>/detail_vanne', views.detailVanne, name='detail_vanne'),

    path('vanne/<int:id_vanne>/delete', views.delete, name='delete'),
    path('vanne/<int:id_vanne>/print', views.printer, name='print'),
    path('vanne/<int:id_vanne>/rechange', views.rechange, name='rechange'),
    path('vanne/<int:id_vanne>/recover', views.recover, name='recover'),
    path('vanne/<int:id_vanne>/recoverBIS', views.recoverBIS, name='recoverBIS'),
    path('vanne/<int:id_vanne>/edit', views.traitementModifVanne, name='edit'),


    path('vanne/<int:id_vanne>/revision', views.revision, name='revision'),
    path('vanne/<int:id_vanne>/traitement_revision', views.TraitementRevision, name='traitement_revision'),
    path('vanne/<int:id_revision>/detailrevision', views.detail_revision, name='detail_revision'),
    path('vanne/<int:id_vanne>/add_commentaire', views.add_commentaire, name='add_commentaire'),

    path('vanne/<int:id_vanne>/supprimerTotal', views.supressionTOTAL, name='supprimerTotal'),
    path("historique/", views.historiqueVanne, name="historique"),
    path("ajoutVanne/", views.ajoutVanne, name="ajoutVanne"),
    path("ajoutVanne/traitementAjoutVanne/", views.traitementAjoutVanne, name="traitementAjoutVanne"),
    path("ajoutVanne/traitementModifVanne/", views.traitementModifVanne, name="traitementModifVanne"),
    path("vanne/traitement_com/", views.traitement_com, name="traitement_com"),
    path("fusion/", views.fusionner_fournisseurs, name="fusionner_fournisseurs"),
    path("founisseurs/", views.listefournisseur, name="liste_fournisseur"),
    path("renomer/", views.renomer_fournisseurs, name="renomer_fournisseurs"),

]

handler404 = 'appliVanne.views.handler404'
handler500 = 'appliVanne.views.handler500'

EntretienVannes/appliVanne/forms.py
from django import forms
from django.forms import ModelForm
from appliVanne.models import *
from django.core.exceptions import ValidationError
from django.utils import timezone
from tinymce.widgets import TinyMCE
import datetime


class VanneForm(ModelForm):
    #information general à la vannes
    
    id_vanne = forms.IntegerField(label="ID Vanne", required=False)
    nouveau_atelier = forms.CharField(label="Information générales : Nouvel Atelier", required=False)
    id_atelier = forms.ModelChoiceField(queryset=ATELIER.objects.all(), empty_label="Information générales : Sélectionnez un atelier", required=False)
    id_fournisseur = forms.ModelChoiceField(queryset=FOURNISSEUR.objects.all(),empty_label="Corps : Sélectionnez un fournisseur",required=False,label="fournisseur")

    type_vanne = forms.ChoiceField(choices=(('TOR', 'TOR'), ('REG', 'REG')), label="Type de vanne", required=True)
    tempsRev = forms.IntegerField(label="Temps de révision", required=False, error_messages={'required': 'Ce champ est obligatoire.'})
    date_de_la_commande = forms.DateField(label="Information générales : Date de la commande", required=False)
    
    
    
    #CORPS
    nouveau_atelier = forms.CharField(label="Corps : Nouvel Atelier", required=False)
    nouveau_fournisseur = forms.CharField(label="Corps : Nom du Nouveau Fournisseur",required=False)  # Rendre ce champ optionnel)
    taille_corps = forms.CharField(label="Corps : Taille du corps",required=False)
    code_corps = forms.CharField(label="Corps : Code du corps",required=False) 
    type_corps = forms.CharField(label="Corps : Type de corps",required=False)
    pn_corps = forms.CharField(label="Corps : PN Corps", required=False)
    cv_corps = forms.CharField(label="Corps : CV Corps", required=False)
    numero_serie_corps = forms.CharField(label="Corps : Numéro de série corps", required=False)
    corps_corps = forms.CharField(label="Corps : Matière du corps", required=False)
    norme_bride_corps = forms.CharField(label="Corps : Norme bride corps", required=False)
    garniture_corps = forms.CharField(label="Corps : Garniture corps", required=False)
    type_garniture = forms.CharField(label="Corps : Type Ganiture corps", required=False)    
    matiere_arbre = forms.CharField(label="Corps : Matière arbre", required=False)
    matiere_siege = forms.CharField(label="Corps : Matière siège", required=False)
    matiere_organe_reglant = forms.CharField(label="Corps : Matière organe réglant", required=False)

    #ACTIONNEUR
    id_fournisseur_actionneur = forms.ModelChoiceField(queryset=FOURNISSEUR.objects.all(),empty_label="Actionneur : Sélectionnez un fournisseur",required=False,label="fournisseur")
    nouveau_fournisseur_actionneur = forms.CharField(label="Actionneur : Nom du Nouveau Fournisseur",required=False)  # Rendre ce champ optionnel)
    taille_actionneur = forms.CharField(label="Actionneur : Taille de l'actionneur",required=False)
    type_actionneur = forms.CharField(label="Actionneur : Type d'actionneur",required=False)
    numero_serie_actionneur = forms.CharField(label="Actionneur : Numéro de serie" ,required=False)
    commande_manuelle_actionneur = forms.ChoiceField(choices=[('OUI', 'OUI'), ('NON', 'NON') ], required=False)
    sens_actionneur = forms.ChoiceField(choices=[('OMA', 'OMA'), ('FMA', 'FMA')],required=False)
    pression_alimentation = forms.CharField(label="Actionneur : Pression Alim." ,required=False)
    type_contact = forms.CharField(label="Actionneur : Type Contact" ,required=False)
    type_effet = forms.ChoiceField(choices=[('SIMPLE', 'SIMPLE'), ('DOUBLE', 'DOUBLE')],required=False)
    type_contact_actionneur = forms.ChoiceField(choices=[('OUVERTURE', 'OUVERTURE'), ('FERMETURE', 'FERMETURE'), ('FERM+OUVER', 'OUVERTURE + FERMETURE')],required=False)

    #POSITIONNEUR
    presence_positionneur = forms.ChoiceField(choices=[(0, 'NON'), (1, 'OUI')])
    id_fournisseur_positionneur = forms.ModelChoiceField(queryset=FOURNISSEUR.objects.all(),empty_label="Sélectionnez un fournisseur",required=False,label="fournisseur")
    nouveau_fournisseur_positionneur = forms.CharField(label="Nom du Nouveau Fournisseur",required=False)  # Rendre ce champ optionnel)
    id_fonctionnement_positionneur = forms.ModelChoiceField(queryset=TYPEPOSITIONNEUR.objects.all(),required=False,label="fonctionnement")
    type_positionneur = forms.CharField(label="Positionneur : Type de positionneur", required=False)
    numero_serie_positionneur = forms.CharField(label="Positionneur : Numéro de serie" , required=False)
    signal_sortie_positionneur = forms.CharField(label="Positionneur : Signal de sortie" , required=False)
    signal_entree_positionneur = forms.CharField(label="Positionneur : Signal d'entrée" , required=False)
    repere_came_positionneur = forms.CharField(label="Positionneur : Repère de la came" , required=False)
    face_came_positionneur = forms.CharField(label="Positionneur : Face de la came" , required=False)
    sens_action = forms.ChoiceField(choices=[('DIRECT', 'DIRECT'), ('INVERSE', 'INVERSE')],required=False)
    fermee_a_positionneur = forms.CharField(label="Positionneur : Fermée à", required=False )
    ouverte_a_positionneur = forms.CharField(label="Positionneur : Ouverte à" , required=False)
    alimentation_positionneur = forms.CharField(label="Positionneur : Alimentation" , required=False)
    loi_commande_positionneur = forms.CharField(label="Loi" , required=False )
    
    infoRevisionBIS = forms.ChoiceField(choices=[(0, 'NON'), (1, 'OUI')])#a revoir
    repere_vanne = forms.CharField(label="Repère de la vanne", required=True)
    affectation_vanne = forms.CharField(label="Affectation de la vanne", required=True)
    numero_commande = forms.CharField(label="Numéro de la commande", required=False)
    
    class Meta:
        model = Vanne
        fields = ['repere_vanne', 'affectation_vanne', 'numero_commande']
      
    
    def clean(self):
        cleaned_data = super().clean()
        num_atelier = cleaned_data.get("id_atelier")  # Assurez-vous que cela correspond au nom du champ dans votre modèle/formulaire
        nouveau_atelier = cleaned_data.get("nouveau_atelier")

        if num_atelier == -1 and not nouveau_atelier:
            raise ValidationError("Veuillez fournir le nom du nouvel atelier.")

        # Vous pouvez ajouter d'autres validations ici si nécessaire


        # Liste des champs à exclure
        champs_exclus = [
            'affectation_vanne', 'sens_action', 'infoRevisionBIS', 
            'presence_positionneur', 'type_contact_actionneur', 'type_effet',
            'sens_actionneur', 'commande_manuelle_actionneur', 'type_vanne'
        ]

        for field_name, value in cleaned_data.items():
            # S'assure que le champ n'est pas dans la liste des exclus et que la valeur n'est pas None
            if field_name not in champs_exclus and value is not None and isinstance(value, str):
                # Supprime tous les espaces
                value = value.replace(" ", "")
                # Remplace les virgules par des points
                value = value.replace(",", ".")
                # Convertit tout en majuscules
                value = value.upper()

                # Après transformation, vérifie si la valeur est une chaîne vide ou 'NONE'
                if value == '' or value == 'NONE':  # Pas besoin de strip ici car il n'y a pas d'espace
                    cleaned_data[field_name] = None
                else:
                    cleaned_data[field_name] = value
            # Si le champ est dans les exclus ou la valeur est None, il n'est pas modifié
            # Ajoutez ici toute autre condition spécifique pour d'autres types de champs si nécessaire

                
        date_commande = cleaned_data.get("date_de_la_commande")
        print ("test date commande")
        print(date_commande)
        print ("fin test date commande")

        
        if not date_commande:
            print ("TEST 2 date commande")
            print (self.cleaned_data['date_de_la_commande'])
            self.cleaned_data['date_de_la_commande'] = timezone.now().date()
            print ("TEST 2 FIN date commande")

        return cleaned_data

        
    
class CommentForm(forms.ModelForm):
    
    commentaire = forms.CharField(label="Revision" , required=True,  widget=TinyMCE(attrs={'cols': 80, 'rows': 30}) )

    class Meta:
        model = REVISON
        fields = ['commentaire']
        
        
class ajoutDeCom(forms.ModelForm):
    detail_commentaire = forms.CharField(label="Commentaire", required=False, widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    id_type_revision = forms.ModelChoiceField(queryset=TypeRevision.objects.all(), empty_label="Sélectionnez un type de commentaire", required=False, label="Type de commentaire")
    nouveau_type_commentaire = forms.CharField(label="Nouveau type de commentaire", required=False)
    object_commentaire = forms.CharField(label="Objet", required=True)
    
    class Meta:
        model = REVISON
        fields = ['detail_commentaire', 'object_commentaire']
        
    def clean(self):
        cleaned_data = super().clean()
        id_type_revision = cleaned_data.get("id_type_revision")        

class FusionFournisseurForm(forms.Form):
    fournisseurs_a_fusionner = forms.ModelMultipleChoiceField(queryset=FOURNISSEUR.objects.all(), widget=forms.CheckboxSelectMultiple)
    nouveau_nom = forms.CharField(max_length=100)
    
    
class renomerFournisseurForm(forms.Form):
        fournisseurs_a_renomer = forms.ModelChoiceField(queryset=FOURNISSEUR.objects.all(),required=True,label="Fournisseur à renommer")
        nouveau_nom = forms.CharField(max_length=100, label="Nouveau nom du fournisseur")

EntretienVannes/appliVanne/templates/appliVanne/actionneur.html
{% extends "appliVanne/base.html" %} {% block title %} Les Actionneur {% endblock %}
{% block main %}
  
<!--

  Tableau avec liste des vanne  et le info suivante : 
    - numéro de la vanne
    - nom de l'atelier
    - repere de la vanne
    - affectation de la vanne
    - type de vanne

  option pour voir en detail, mettre à jour et supprimer la vanne

  <thead>
  <tr>
    <th scope="col"><a href="?tri=id_vanne&ordre={% cycle 'asc' 'desc' %}">Identifiant</a></th>
    <th scope="col"><a href="?tri=id_atelier__nom_atelier&ordre={% cycle 'asc' 'desc' %}">Atelier</a></th>
    <th scope="col"><a href="?tri=repere_vanne&ordre={% cycle 'asc' 'desc' %}">Repere Vannes</a></th>
 

-->
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"> Identifiant</th>
        <th scope="col">Fournisseur</th>
        <th scope="col">Fonctionnement </th>
        <th scope="col">Affectation </th>
        <th scope="col">Type </th>
      </tr>
    </thead>

    {% for act in listeAct %}
      <tr>
        <td>{{ act.id_actionneur}}</td>
        <td>{{ act.id_fournisseur.nom_fournisseur}}</td>
        <td>{{ act.type_actionneur}}</td>
        <td>{{ act.num_serie_actionneur}}</td>
        <td>{{ act.taille_actionneur }}</td>
      </tr>
    {% endfor %}
  </table>



{% endblock %}

EntretienVannes/appliVanne/templates/appliVanne/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
   <!-- <meta name="viewport" content="width=device.width, initial-scale=1" />-->
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'appliVanne/CSS/styles.css' %}" />
    <link rel="icon" href="{% static 'appliVanne/IMG/logoSimple.ico' %}" />
    {% block extra_css %}{% endblock %}
    {% block extra_js %}{% endblock %}
    
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    
  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
    </script>
  </head>
  <body>
    <header>
      {% if user.is_superuser %}
      {% include "./menuADMIN.html"%}

      {% elif  user.is_authenticated%}
      {% include "./menu.html" %}
      
      {%else%}
      {% include "./menuNonConnecter.html" %}
      {%endif%}

    </header>

    <main>{%block main%} {% endblock %}</main>

    

    
    <footer>{% include "./footer.html" %}</footer>
    

  </script>
  <script src="{% static 'appliVanne/JS/jsGeneral.js' %}"></script>
  </body>
</html>

EntretienVannes/appliVanne/templates/appliVanne/comentaire.html
{% extends "appliVanne/base.html" %}
{% load static %} 
{% block title %} Révision {% endblock %}

{% block main %}
<style>
    

    .container {
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }

    .jumbotron {
        background-color: #e9ecef;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
    }

    .form-control {
        border-radius: 4px;
        border: 1px solid #ced4da;
        padding: 10px;
        width: 100%;
        box-sizing: border-box;
        margin-bottom: 10px;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .card {
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
        margin-bottom: 20px;
    }

    .card-header {
        background-color: #007bff;
        color: #ffffff;
        border-radius: 8px 8px 0 0;
        padding: 10px 15px;
    }

    .list-group-flush {
        padding: 15px;
    }

    button {
        background-color: #007bff;
        color: #ffffff;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.2s ease-in-out;
    }

    button:hover {
        background-color: #0056b3;
    }
</style>

<form method="post" action = "{% url 'traitement_com' %}">
    {% csrf_token %}
<div style="margin-bottom:70px" class="container mt-4">
    <div class="jumbotron">
        {% if form.errors %}
        <div class="alert alert-danger">
            <strong>Erreur(s) lors de la soumission du formulaire :</strong>
            <ul>
                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <li><strong>{{ field.label|capfirst }}:</strong> {{ error }}</li>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <input type="hidden" name="id_vanne" value="{{ vanne.id_vanne }}">

        

        <h1 class="display-4">Commentaire n°{{lesRev}}</h1>
        <p class="lead">Commentaire du <script>var today = new Date(); document.write(today.toLocaleDateString());</script></p>
        <hr class="my-4">
        <p><strong>Type d'ajout :</strong> MANUELLE</p>

        <label for="id_type_revision"><strong>Type de commentaire:</strong></label>
        <select name="id_type_revision" id="id_type_revision" class="form-control">
            {% for type in lesTypeRev %}
                <option value="{{type.id_type_revision}}" {% if request.POST.id_type_revision|stringformat:"s" == type.id_type_revision|stringformat:"s" %}selected{% endif %}>{{ type.type_revision }}</option>
            {% endfor %}
        </select>
        
        <div class="form-group" id="nouveau_type_rev" style="display:none;">
            <label for="nouveau_type_commentaire"> <strong>Nouveau type de commentaire:</strong></label>
            <input type="text" name="nouveau_type_commentaire" id="nouveau_type_commentaire" class="form-control" value="{{ request.POST.nouveau_type_commentaire|default:'' }}">
        </div>
        
        <p><strong>Nom du technicien : </strong>{{ request.user.first_name }}  {{request.user.last_name }}</p>

        <label for="object_commentaire"><strong>Objet du commentaire:</strong></label>
        <input type="text" name="object_commentaire" id="object_commentaire" class="form-control" value="{{ request.POST.object_commentaire|default:'' }}">
    </div>

    <div class="card">
        <div class="card-header"><strong>Détails du commentaire</strong></div>
        <ul class="list-group list-group-flush">
            <textarea id="detail_commentaire" name="detail_commentaire" rows="30">{{request.POST.detail_commentaire}}</textarea>
        </ul>
        <button type="submit">Enregistrer</button>
    </div>
</div>

<script src="//cdn.tiny.cloud/1/u4yuqji0ycc8q23g117hclj1pzkkb75a94jn8shw20c97jkz/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
      selector: '#detail_commentaire'
      // ... autres options d'initialisation ...
    });
</script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var selectTypeCommentaire = document.getElementById('id_type_revision');
        var divNouveauType = document.getElementById('nouveau_type_rev');
        
        // Fonction pour mettre à jour l'affichage de divNouveauType
        function updateDivDisplay() {
            if(selectTypeCommentaire.value === '6') { // Assurez-vous que '6' est l'ID correct pour "Autre ..."
                divNouveauType.style.display = 'block';
            } else {
                divNouveauType.style.display = 'none';
            }
        }

        // Ajoutez l'écouteur d'événement pour le changement de valeur
        selectTypeCommentaire.addEventListener('change', updateDivDisplay);

        // Appelez updateDivDisplay au chargement pour initialiser l'affichage correctement
        updateDivDisplay();
    });
</script>


{% endblock %}

EntretienVannes/appliVanne/templates/appliVanne/footer.html
© Appli Vannes 2023 ©
<p> © Dev by Nathan GILBERT © </p>

EntretienVannes/appliVanne/templates/appliVanne/listeFournisseur.html
{% extends "appliVanne/base.html" %} {% block title %} Les Actionneur {% endblock %}
{% block main %}
  
<!--

  Tableau avec liste des vanne  et le info suivante : 
    - numéro de la vanne
    - nom de l'atelier
    - repere de la vanne
    - affectation de la vanne
    - type de vanne

  option pour voir en detail, mettre à jour et supprimer la vanne

  <thead>
  <tr>
    <th scope="col"><a href="?tri=id_vanne&ordre={% cycle 'asc' 'desc' %}">Identifiant</a></th>
    <th scope="col"><a href="?tri=id_atelier__nom_atelier&ordre={% cycle 'asc' 'desc' %}">Atelier</a></th>
    <th scope="col"><a href="?tri=repere_vanne&ordre={% cycle 'asc' 'desc' %}">Repere Vannes</a></th>
 

-->
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"> Identifiant</th>
        <th scope="col">Fournisseur</th>
        <th scope="col">Numero tel </th>
        <th scope="col">Email </th>

      </tr>
    </thead>

    {% for fourn in lesFournisseur %}
      <tr>
        <td>{{ fourn.id_fournisseur}}</td>
        <td>{{ fourn.nom_fournisseur}}</td>
        <td>{{ fourn.tel_founisseur}}</td>
        <td>{{ fourn.email_fournisseur}}</td>

      </tr>
    {% endfor %}
  </table>



{% endblock %}

EntretienVannes/appliVanne/templates/appliVanne/menuNonConnecter.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: darkred;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{%static 'appliVanne/IMG/logoLong.ico' %}" class="logo" />
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
      aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/vannes/" style="color:white">Vannes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/rechangeREG/" style="color:white">Rechange REG</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/rechangeTOR/" style="color:white">Rechange TOR</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/historique/" style="color:white">Historique</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/recherche/" style="color:white">RECHERCHER</a>
        </li>
      </ul>
      
      <a class="nav-link" href="/login/" style="color:white">Se Connecter</a>
    
              

    
        
    </div>
  </div>
</nav>

EntretienVannes/appliVanne/templates/appliVanne/revision.html
{% extends "appliVanne/base.html" %}
{% load static %} {% block title %} Révision {% endblock %}


    
{% block main %}


<style>
    .container {
        width: 80%;
        margin: auto;
        padding-top: 20px;
    }
    
    .jumbotron {
        background-color: #f8f9fa;
        border-radius: 5px;
        padding: 20px;
        box-shadow: 0 2px 4px rgba(0,0,0,.1);
    }
    
    .card {
        border: 1px solid #ddd;
        margin-top: 20px;
    }
    
    .card-header {
        background-color: #f7f7f7;
        font-weight: bold;
    }
    
    .list-group-item {
        border: none;
        border-bottom: 1px solid #eee;
    }
    
    .list-group-item:last-child {
        border-bottom: none;
    }
    
    /* Vous pouvez ajouter des styles personnalisés ici */
    
</style>
<div style = "margin-bottom:70px" class="container mt-4">
    <div class="jumbotron">
        <h1 class="display-4">Commentaire n°{{lesRev}}</h1>
        <p class="lead">Révision du <script>var today = new Date(); document.write( today.toLocaleDateString() ); </script></p>
        <hr class="my-4">
        <p>Type d'ajout : MANUELLE</p>
        <p>Type de commentaire: Révision</p>
        <p>Nom du technicien : {{ request.user.first_name }}  {{request.user.last_name }}</p>
        <p>Commentaire : Revision effectué</p>

    </div>

    <div class="card">
        <div class="card-header">
            Détails de la Révision
        </div>
        <ul class="list-group list-group-flush">
            <form method="post" action="traitement_revision">
            {% csrf_token %}
            <textarea id="id_commentaire" name="commentaire" rows="30"></textarea>
            

        </ul>
        <button  type="submit">Enregistrer</button>
    </div>
</div>



    <script src="//cdn.tiny.cloud/1/u4yuqji0ycc8q23g117hclj1pzkkb75a94jn8shw20c97jkz/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
    tinymce.init({
      selector: '#id_commentaire'
      // ... autres options d'initialisation ...
    });
    </script>
{% endblock %}